### ISSUE TITLE
Maquetar informacion de destino en vista de Producto

### ISSUE THREAD

**Issue by M4gnus99** [unzagaf/grupo_4_ValleDorado#10]
COMO usuario QUIERO visualizar la informacion del destino PARA conocer los datos basicos del destino seleccionado

**Comment by AldaCeleste** [comment]
Se muestran fotos del lugar elegido, con las descripciones de los dias de alojamiento ,el costo del mismo.
Se muetran las cosas principales que incluye el servicio y las que no entran dentro del paquete, como asi tambien un resumen del itinerario
